DescuentarMVC/Descuentar/Models/Cupon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Descuentar.Models
{
    public class Cupon
    {
        [Key]
        public int ID { get; set; }
        [Required]
        public String description { get; set; }
        [Required]
        public String companyName { get; set; }
        [Required]
        public double Discount { get; set; }
        [Required]
        public int life { get; set; }
        [Required]
        public int likes { get; set; }
    }
}

DescuentarMVC/Descuentar/Controllers/CuponsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Descuentar.Models;

namespace Descuentar.Controllers
{
    public class CuponsController : Controller
    {
        private readonly Context _context;

        public CuponsController(Context context)
        {
            _context = context;
        }

        // GET: Cupons
        public async Task<IActionResult> Index()
        {
            return View(await _context.cupons.ToListAsync());
        }

        // GET: Cupons/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cupon = await _context.cupons
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cupon == null)
            {
                return NotFound();
            }

            return View(cupon);
        }

        // GET: Cupons/Thanks/5
        public async Task<IActionResult> Thanks(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cupon = await _context.cupons
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cupon == null)
            {
                return NotFound();
            }

            return View();
        }

        // GET: Cupons/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Cupons/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,description,companyName,Discount,life,likes")] Cupon cupon)
        {
            if (ModelState.IsValid)
            {
                _context.Add(cupon);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(cupon);
        }

        // GET: Cupons/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cupon = await _context.cupons.FindAsync(id);
            if (cupon == null)
            {
                return NotFound();
            }
            return View(cupon);
        }

        // POST: Cupons/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,description,companyName,Discount,life,likes")] Cupon cupon)
        {
            if (id != cupon.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(cupon);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CuponExists(cupon.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(cupon);
        }

        // GET: Cupons/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cupon = await _context.cupons
                .FirstOrDefaultAsync(m => m.ID == id);
            if (cupon == null)
            {
                return NotFound();
            }

            return View(cupon);
        }

        // POST: Cupons/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cupon = await _context.cupons.FindAsync(id);
            _context.cupons.Remove(cupon);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CuponExists(int id)
        {
            return _context.cupons.Any(e => e.ID == id);
        }
    }
}

DescuentarMVC/Descuentar/Controllers/LikerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Descuentar.Models;
using Microsoft.AspNetCore.Mvc;

namespace Descuentar.Controllers
{
    public class LikerController : Controller
    {
        private readonly Context _context;

        public LikerController(Context context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return RedirectToAction("updateLikes");
        }

        [HttpPost]
        public IActionResult UpdateLikes(Cupon cupon)
        {
            return Json(new { data = DarLike(cupon.ID) });
        }

        private int DarLike(int id)
        {
            Cupon cupon = _context.cupons.Find(id);
            cupon.likes++;
            _context.cupons.Update(cupon);
            _context.SaveChanges();
            return cupon.likes;
        }
    }
}

DescuentarMVC/Descuentar/Views/Cupons/Create.cshtml
@model Descuentar.Models.Cupon

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Cupon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="companyName" class="control-label"></label>
                <input asp-for="companyName" class="form-control" />
                <span asp-validation-for="companyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="life" class="control-label"></label>
                <input asp-for="life" class="form-control" />
                <span asp-validation-for="life" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="likes" class="control-label"></label>
                <input asp-for="likes" class="form-control" />
                <span asp-validation-for="likes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DescuentarMVC/Descuentar/Views/Cupons/Delete.cshtml
@model Descuentar.Models.Cupon

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Cupon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.companyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.companyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.life)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.life)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.likes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.likes)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

DescuentarMVC/Descuentar/Views/Cupons/Details.cshtml
@model Descuentar.Models.Cupon

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Cupon</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.companyName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.companyName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Discount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Discount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.life)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.life)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.likes)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.likes)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

DescuentarMVC/Descuentar/Views/Cupons/Edit.cshtml
@model Descuentar.Models.Cupon

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Cupon</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="description" class="control-label"></label>
                <input asp-for="description" class="form-control" />
                <span asp-validation-for="description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="companyName" class="control-label"></label>
                <input asp-for="companyName" class="form-control" />
                <span asp-validation-for="companyName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Discount" class="control-label"></label>
                <input asp-for="Discount" class="form-control" />
                <span asp-validation-for="Discount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="life" class="control-label"></label>
                <input asp-for="life" class="form-control" />
                <span asp-validation-for="life" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="likes" class="control-label"></label>
                <input asp-for="likes" class="form-control" />
                <span asp-validation-for="likes" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DescuentarMVC/Descuentar/Views/Cupons/Index.cshtml
@model IEnumerable<Descuentar.Models.Cupon>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.companyName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Discount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.life)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.likes)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr id="@item.ID">
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.description)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.companyName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Discount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.life)
            </td>
            <td name="like">
                @Html.DisplayFor(modelItem => item.likes)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ID">Delete</a> |
                <a asp-action="Thanks" asp-route-id="@item.ID">Copy Cupon</a> |
                <button onclick="postLike(@item.ID)">Like!</button>
            </td>
        </tr>
}
    </tbody>
</table>
<script>
    const postLike = id => {
        console.log(id);
        $.ajax({
            type: "POST",
            url: '@Url.Action("UpdateLikes", "Liker")',
            data: JSON.stringify({ ID: id }),
            dataType: "json",
            contentType: "application/json; charset=utf-8",
            success: function (response) {
                document.getElementById(id).querySelectorAll('[name=like]')[0].innerHTML = response.data;
            },
            failure: function (response) {
                alert(response.responseText);
            },
            error: function (response) {
                alert(response.responseText);
            }
        });
    }
</script>

DescuentarMVC/Descuentar/Views/Cupons/Thanks.cshtml
@model IEnumerable<Descuentar.Models.Cupon>

@{
    ViewData["Title"] = "Index";
}

<h1>Thanks!</h1>
<p>Ýour cupon id is @Html.DisplayNameFor(model => model.ID) </p>
<p>To use it just paste it or copy it. (Keseio)</p>